import { FaWifi, FaSwimmer, FaConciergeBell, FaCar, FaUtensils, FaDumbbell, FaSpa } from "react-icons/fa";
import { MdLocalLaundryService, MdPets, MdOutlineAir } from "react-icons/md";

const hotels = [
  {
    id: 1,
    name: "Hotel Sunshine",
    description: "A luxurious stay in the heart of the city.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop&q=60",
    location: "Mumbai, India",
    price: 120,
    rating: 4.5,
    reviews: 320,
    facilities: [
      { name: "Free WiFi", icon: <FaWifi /> },
      { name: "Swimming Pool", icon: <FaSwimmer /> },
      { name: "Room Service", icon: <FaConciergeBell /> },
      { name: "Parking", icon: <FaCar /> },
    ],
  },
  {
    id: 2,
    name: "Oceanview Resort",
    description: "Enjoy breathtaking views of the ocean.",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600&auto=format&fit=crop&q=60",
    location: "Goa, India",
    price: 180,
    rating: 4.7,
    reviews: 410,
    facilities: [
      { name: "Beach Access", icon: <FaUtensils /> },
      { name: "Swimming Pool", icon: <FaSwimmer /> },
      { name: "Laundry Service", icon: <MdLocalLaundryService /> },
      { name: "Pets Allowed", icon: <MdPets /> },
    ],
  },
  {
    id: 3,
    name: "Mountain Retreat",
    description: "A peaceful escape in the mountains.",
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600&auto=format&fit=crop&q=60",
    location: "Manali, India",
    price: 150,
    rating: 4.6,
    reviews: 290,
    facilities: [
      { name: "Spa & Wellness", icon: <FaSpa /> },
      { name: "Free WiFi", icon: <FaWifi /> },
      { name: "Air Conditioning", icon: <MdOutlineAir /> },
    ],
  },
  {
    id: 4,
    name: "Lakeside Paradise",
    description: "A tranquil retreat by the lake.",
    image: "https://images.unsplash.com/photo-1566195992011-5f6b21e539aa?q=80&w=1974&auto=format&fit=crop",
    location: "Udaipur, India",
    price: 170,
    rating: 4.8,
    reviews: 500,
    facilities: [
      { name: "Free WiFi", icon: <FaWifi /> },
      { name: "Swimming Pool", icon: <FaSwimmer /> },
      { name: "Parking", icon: <FaCar /> },
      { name: "Gym", icon: <FaDumbbell /> },
    ],
  },
  {
    id: 5,
    name: "Cityscape Inn",
    description: "Experience modern luxury in the city center.",
    image: "https://plus.unsplash.com/premium_photo-1661879252375-7c1db1932572?w=600&auto=format&fit=crop&q=60",
    location: "Delhi, India",
    price: 200,
    rating: 4.9,
    reviews: 620,
    facilities: [
      { name: "Spa & Wellness", icon: <FaSpa /> },
      { name: "Room Service", icon: <FaConciergeBell /> },
      { name: "Laundry Service", icon: <MdLocalLaundryService /> },
      { name: "Air Conditioning", icon: <MdOutlineAir /> },
    ],
  },
  {
    id: 6,
    name: 'Desert Mirage Hotel',
    description: 'An oasis of comfort in the heart of the desert.',
    image: 'https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D',
    location: "Delhi, India",
    price: 200,
    rating: 4.9,
    reviews: 620,
    facilities: [
      { name: "Spa & Wellness", icon: <FaSpa /> },
      { name: "Room Service", icon: <FaConciergeBell /> },
      { name: "Laundry Service", icon: <MdLocalLaundryService /> },
      { name: "Air Conditioning", icon: <MdOutlineAir /> },
    ],
  },
  {
    id: 7,
    name: 'Forest Hideaway',
    description: 'Surrounded by lush greenery and wildlife.',
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D',
    location: "Delhi, India",
    price: 200,
    rating: 4.9,
    reviews: 620,
    facilities: [
      { name: "Spa & Wellness", icon: <FaSpa /> },
      { name: "Room Service", icon: <FaConciergeBell /> },
      { name: "Laundry Service", icon: <MdLocalLaundryService /> },
      { name: "Air Conditioning", icon: <MdOutlineAir /> },
    ],
  },
  {
    id: 8,
    name: 'Cozy Cottage',
    description: 'A charming and cozy cottage stay.',
    image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjh8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D',
    location: "Delhi, India",
    price: 200,
    rating: 4.9,
    reviews: 620,
    facilities: [
      { name: "Spa & Wellness", icon: <FaSpa /> },
      { name: "Room Service", icon: <FaConciergeBell /> },
      { name: "Laundry Service", icon: <MdLocalLaundryService /> },
      { name: "Air Conditioning", icon: <MdOutlineAir /> },
    ],
  },
  {
    id: 9,
    name: 'Skyline Suites',
    description: 'Panoramic views of the city skyline.',
    image: 'https://images.unsplash.com/photo-1621293954908-907159247fc8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzR8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D',
    location: "Delhi, India",
    price: 200,
    rating: 4.9,
    reviews: 620,
    facilities: [
      { name: "Spa & Wellness", icon: <FaSpa /> },
      { name: "Room Service", icon: <FaConciergeBell /> },
      { name: "Laundry Service", icon: <MdLocalLaundryService /> },
      { name: "Air Conditioning", icon: <MdOutlineAir /> },
    ],
  },
];

export default hotels;
